region: ap-southeast-2
template_bucket_name: alexharvey3118

hooks:
  before_create:
    - !cmd "./hooks/build.sh alexharvey3118 https://github.com/alexharv074/sceptre-sam-poc/releases/download/v1.0.0/sam.zip"

  after_create:
    - !cmd "./hooks/cleanup.sh alexharvey3118"
